export const searchData = [
  {
    slug: 'coxs-bazar',
    title: 'Entire apartment hosted by Manirul Islam',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      "Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.",
    image: 'https://i.ibb.co/nzPVT0m/ocean-paradise-hotel.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'coxs-bazar',
    title: 'Luxurious hotel hosted by Saint Martin',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      "Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.",
    image: 'https://i.ibb.co/8gSSnRv/room-of-hotel-ocean-paradise.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'coxs-bazar',
    title: 'Fabulous apartment hosted by hotel cox',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      "Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.",
    image: 'https://i.ibb.co/Bcgwyw6/1196495-17122303270060592602.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sreemangal',
    title: 'Fabulous apartment hosted by hotel cox',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sreemangal is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/Bcgwyw6/1196495-17122303270060592602.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sreemangal',
    title: 'Entire apartment hosted by Manirul Islam',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sreemangal is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/8gSSnRv/room-of-hotel-ocean-paradise.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sreemangal',
    title: 'Luxurious hotel hosted by Saint Martin',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sreemangal is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/nzPVT0m/ocean-paradise-hotel.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sundarban',
    title: 'Entire apartment hosted by Manirul Islam',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sundarban is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/nzPVT0m/ocean-paradise-hotel.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sundarban',
    title: 'Luxurious hotel hosted by Saint Martin',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sundarban is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/8gSSnRv/room-of-hotel-ocean-paradise.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
  {
    slug: 'sundarban',
    title: 'Luxurious hotel hosted by hotel cox',
    guest: 4,
    bathrooms: 3,
    beds: 5,
    baths: 2,
    description:
      'Sundarban is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.',
    image: 'https://i.ibb.co/Bcgwyw6/1196495-17122303270060592602.jpg',
    ratings: 4,
    totalRatings: 20,
    amount: 34,
  },
];
